#!/bin/sh
set -u
if [ $# -ne 1 ]; then
   echo "You should specify post title." 1>&2
   exit 1;
fi

cd `dirname $0`
post=`bundle exec jekyll post $1 | grep 'New post created' | gsed 's/^New post created at \([^.]*\.md\).*$/\1/'`
post=`ruby refine-post.rb $post`
$BLOG_EDITOR $post
