---
layout: empty
---
{% raw %}
backend:
  name: github
  repo: skoji/skoji.jp-source
  branch: main
  base_url: https://decap-auth.skoji.jp
media_folder: 'images'
public_folder: '/blog/images/'
site_url: https://skoji.jp/blog/
editor:
  preview: false
collections:
  - name: 'blog'
    label: 'Blog'
    create: true
    path: "{{year}}/{{slug}}"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    folder: "_posts"
    preview_path: '/blog/{{year}}/{{month}}/{{title}}.html'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', picker_utc: false, format: "YYYY-MM-DDTHH:mm:ssZ", widget: 'datetime' }
      - { label: 'OGP Image', name: 'image', widget: 'image', required: false }
      - label: 'Font'
        name: 'type'
        widget: 'select'
        options:
          - { label: 'default', value: '' }
          - { label: 'sans-serif', value: 'sans-serif' }
          - { label: 'serif', value: 'serif' }
        required: false
      - label: 'Categories'
        name: 'categories'
        widget: 'select'
        multiple: true
        options: [{% endraw %}{% for category in site.categories %}"{{ category[0] }}"{% unless forloop.last %}, {% endunless %}{% endfor %}{% raw %}]
      - { label: 'Body', name: 'body', widget: 'markdown' }{% endraw %}
